In [1]:
import pandas as pd
import numpy as np
import os
import glob
from pathlib import Path
from IPython.display import display, HTML
import warnings
warnings.filterwarnings('ignore')

# ── CONFIG ──────────────────────────────────────────────────────────────
# Đổi DATA_DIR thành folder chứa CSV của bạn
DATA_DIR = "/kaggle/input/competitions/datathon-2026-round-1"
NATURAL_NULL_VALUES = {
    'nan', 'NaN', 'null', 'NULL', 'none', 'None',
    '.', '-', '--', 'N/A', 'n/a', 'NA', '',  ' '
}
HIGH_CARD_THRESHOLD = 0.95          # Tỉ lệ unique/total > 95% → likely PK/FK
LOW_CARD_THRESHOLD  = 0.05          # Tỉ lệ unique/total < 5%  → likely category
NULL_WARN_THRESHOLD = 0.20          # Null > 20% → cảnh báo
# ────────────────────────────────────────────────────────────────────────

csv_files = sorted(glob.glob(os.path.join(DATA_DIR, "**/*.csv"), recursive=True) +
                   glob.glob(os.path.join(DATA_DIR, "*.csv")))
csv_files = list(dict.fromkeys(csv_files))  # deduplicate

print(f"📂 DATA_DIR : {os.path.abspath(DATA_DIR)}")
print(f"📄 CSV files: {len(csv_files)} found")
for f in csv_files:
    size_kb = os.path.getsize(f) / 1024
    print(f"   • {Path(f).name:40s}  {size_kb:8.1f} KB")

📂 DATA_DIR : /kaggle/input/competitions/datathon-2026-round-1
📄 CSV files: 14 found
   • customers.csv                               6913.7 KB
   • geography.csv                               1369.4 KB
   • inventory.csv                               5535.8 KB
   • order_items.csv                            23381.6 KB
   • orders.csv                                 44886.0 KB
   • payments.csv                               17952.4 KB
   • products.csv                                 190.6 KB
   • promotions.csv                                 4.3 KB
   • returns.csv                                 2228.0 KB
   • reviews.csv                                 6632.2 KB
   • sales.csv                                    126.6 KB
   • sample_submission.csv                         18.1 KB
   • shipments.csv                              19293.0 KB
   • web_traffic.csv                              203.8 KB

In [2]:
# ── LOAD ALL CSVs ────────────────────────────────────────────────────────
dfs = {}
load_errors = {}

for path in csv_files:
    name = Path(path).stem
    try:
        # Thử detect encoding + đọc sample
        df = pd.read_csv(path)
        dfs[name] = df
        total_rows = sum(1 for _ in open(path, encoding='utf-8', errors='replace')) - 1
        sampled = len(df) < total_rows
        flag = f" (sampled {len(df):,}/{total_rows:,})" if sampled else ""
        print(f"✅ {name:30s}  {len(df):>7,} rows × {len(df.columns):>3} cols{flag}")
    except Exception as e:
        load_errors[name] = str(e)
        print(f"❌ {name}: {e}")

print(f"\nLoaded {len(dfs)}/{len(csv_files)} tables successfully.")

✅ customers                       121,930 rows ×   7 cols
✅ geography                        39,948 rows ×   4 cols
✅ inventory                        60,247 rows ×  17 cols
✅ order_items                     714,669 rows ×   7 cols
✅ orders                          646,945 rows ×   8 cols
✅ payments                        646,945 rows ×   4 cols
✅ products                          2,412 rows ×   8 cols
✅ promotions                           50 rows ×  10 cols
✅ returns                          39,939 rows ×   7 cols
✅ reviews                         113,551 rows ×   7 cols
✅ sales                             3,833 rows ×   3 cols
✅ sample_submission                   548 rows ×   3 cols
✅ shipments                       566,067 rows ×   4 cols
✅ web_traffic                       3,652 rows ×   7 cols

Loaded 14/14 tables successfully.

# 1. Schema & dtypes

In [3]:
def dtype_category(dtype):
    """Map pandas dtype → readable category."""
    s = str(dtype)
    if 'int' in s:   return 'integer'
    if 'float' in s: return 'float'
    if 'bool' in s:  return 'boolean'
    if 'datetime' in s: return 'datetime'
    return 'string/object'

all_schemas = []

for table, df in dfs.items():
    for col in df.columns:
        all_schemas.append({
            'table':   table,
            'column':  col,
            'dtype':   str(df[col].dtype),
            'type':    dtype_category(df[col].dtype),
            'n_rows':  len(df),
        })

schema_df = pd.DataFrame(all_schemas)

# Display per table
for table, grp in schema_df.groupby('table'):
    print(f"\n{'═'*60}")
    print(f"  TABLE: {table.upper()}   ({grp['n_rows'].iloc[0]:,} rows × {len(grp)} cols)")
    print(f"{'═'*60}")
    display(grp[['column','dtype','type']].reset_index(drop=True).style
            .set_table_styles([{'selector':'th','props':[('background','#2d2d2d'),('color','#fff'),('padding','6px 12px')]}])
            .apply(lambda col: ['background: #fff9db' if v == 'string/object' else '' for v in col], subset=['type']))

════════════════════════════════════════════════════════════
  TABLE: CUSTOMERS   (121,930 rows × 7 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: GEOGRAPHY   (39,948 rows × 4 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: INVENTORY   (60,247 rows × 17 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: ORDER_ITEMS   (714,669 rows × 7 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: ORDERS   (646,945 rows × 8 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: PAYMENTS   (646,945 rows × 4 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: PRODUCTS   (2,412 rows × 8 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: PROMOTIONS   (50 rows × 10 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: RETURNS   (39,939 rows × 7 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: REVIEWS   (113,551 rows × 7 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: SALES   (3,833 rows × 3 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: SAMPLE_SUBMISSION   (548 rows × 3 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: SHIPMENTS   (566,067 rows × 4 cols)
════════════════════════════════════════════════════════════

════════════════════════════════════════════════════════════
  TABLE: WEB_TRAFFIC   (3,652 rows × 7 cols)
════════════════════════════════════════════════════════════

# 2. Null % per Column

In [4]:
# ── NORMALIZE NATURAL NULLS ──────────────────────────────────────────────
import re

def normalize_nulls(df: pd.DataFrame, null_values: set) -> tuple[pd.DataFrame, dict]:
    """
    Với mỗi column kiểu object/string:
      1. Strip whitespace đầu/cuối
      2. So sánh (case-sensitive) với null_values
      3. Thay thế bằng np.nan
    Trả về (df_normalized, report) trong đó report ghi lại
    số ô được chuyển đổi per column.
    """
    df = df.copy()
    report = {}  # col → n_converted

    for col in df.select_dtypes(include='object').columns:
        # Strip whitespace (tạo series tạm, không mutate ngay)
        stripped = df[col].str.strip()

        # Mask: stripped value nằm trong null_values (và chưa phải NaN)
        mask = stripped.isin(null_values) & df[col].notna()
        n_converted = int(mask.sum())

        if n_converted > 0:
            df.loc[mask, col] = np.nan
            report[col] = n_converted

    return df, report


# ── Áp dụng lên toàn bộ dfs (in-place update) ───────────────────────────
normalize_summary = []   # dùng cho report
total_converted   = 0

for table in list(dfs.keys()):
    before_nulls = dfs[table].isnull().sum().sum()
    dfs[table], col_report = normalize_nulls(dfs[table], NATURAL_NULL_VALUES)
    after_nulls  = dfs[table].isnull().sum().sum()
    delta        = int(after_nulls - before_nulls)
    total_converted += delta

    normalize_summary.append({
        'table':           table,
        'null_before':     int(before_nulls),
        'null_after':      int(after_nulls),
        'cells_converted': delta,
        'cols_affected':   list(col_report.keys()),
    })

# ── Print report ─────────────────────────────────────────────────────────
print(f"Null normalization — pattern list ({len(NATURAL_NULL_VALUES)} patterns):")
print(' | '.join(sorted(repr(v) for v in NATURAL_NULL_VALUES)))
print()

any_change = False
for row in normalize_summary:
    changed = row['cells_converted'] > 0
    icon    = '🔄' if changed else '✅'
    print(f"{icon} {row['table']:30s}  "
          f"null: {row['null_before']:>6,} → {row['null_after']:>6,}  "
          f"(+{row['cells_converted']:,} cells converted)")
    if changed:
        any_change = True
        for col in row['cols_affected']:
            n = dfs[row['table']][col].isnull().sum()
            print(f"   └─ {col:28s}  null sau normalize: {n:,}")

print()
if total_converted == 0:
    print("✅ Không tìm thấy giá trị thiếu tự nhiên nào. dfs giữ nguyên.")
else:
    print(f"⚠️  Tổng {total_converted:,} ô đã được chuẩn hóa → np.nan.")
    print("   Các bước 2 (Null %), 3 (Cardinality), 4 (FK) sẽ dùng dfs đã normalize.")

Null normalization — pattern list (14 patterns):
' ' | '' | '-' | '--' | '.' | 'N/A' | 'NA' | 'NULL' | 'NaN' | 'None' | 'n/a' | 'nan' | 'none' | 'null'

✅ customers                       null:      0 →      0  (+0 cells converted)
✅ geography                       null:      0 →      0  (+0 cells converted)
✅ inventory                       null:      0 →      0  (+0 cells converted)
✅ order_items                     null: 1,152,816 → 1,152,816  (+0 cells converted)
✅ orders                          null:      0 →      0  (+0 cells converted)
✅ payments                        null:      0 →      0  (+0 cells converted)
✅ products                        null:      0 →      0  (+0 cells converted)
✅ promotions                      null:     40 →     40  (+0 cells converted)
✅ returns                         null:      0 →      0  (+0 cells converted)
✅ reviews                         null:      0 →      0  (+0 cells converted)
✅ sales                           null:      0 →      0  (+0 cells converted)
✅ sample_submission               null:      0 →      0  (+0 cells converted)
✅ shipments                       null:      0 →      0  (+0 cells converted)
✅ web_traffic                     null:      0 →      0  (+0 cells converted)

✅ Không tìm thấy giá trị thiếu tự nhiên nào. dfs giữ nguyên.

In [5]:
null_records = []

for table, df in dfs.items():
    null_counts = df.isnull().sum()
    null_pct    = df.isnull().mean() * 100
    for col in df.columns:
        null_records.append({
            'table':      table,
            'column':     col,
            'null_count': int(null_counts[col]),
            'null_%':     round(float(null_pct[col]), 2),
            'warning':    '⚠️ HIGH NULL' if null_pct[col] > NULL_WARN_THRESHOLD * 100 else ''
        })

null_df = pd.DataFrame(null_records)

# Summary: columns with any nulls
has_nulls = null_df[null_df['null_count'] > 0].copy()

if has_nulls.empty:
    print("✅ No null values detected in any table!")
else:
    print(f"⚠️  {len(has_nulls)} columns have null values:\n")
    
    def null_bar(pct, width=20):
        filled = int(round(pct / 100 * width))
        return '█' * filled + '░' * (width - filled) + f'  {pct:.1f}%'
    
    has_nulls['bar'] = has_nulls['null_%'].apply(null_bar)
    
    for table, grp in has_nulls.groupby('table'):
        print(f"\n── {table} ──")
        for _, row in grp.sort_values('null_%', ascending=False).iterrows():
            warn = row['warning']
            print(f"  {row['column']:30s}  {row['bar']}  ({row['null_count']:,} rows) {warn}")

print(f"\n{'─'*60}")
print("Full null summary:")
display(null_df.sort_values(['table','null_%'], ascending=[True, False])
              .reset_index(drop=True))

⚠️  3 columns have null values:


── order_items ──
  promo_id_2                      ████████████████████  100.0%  (714,463 rows) ⚠️ HIGH NULL
  promo_id                        ████████████░░░░░░░░  61.3%  (438,353 rows) ⚠️ HIGH NULL

── promotions ──
  applicable_category             ████████████████░░░░  80.0%  (40 rows) ⚠️ HIGH NULL

────────────────────────────────────────────────────────────
Full null summary:

          table                    column  null_count  null_% warning
0     customers               customer_id           0     0.0
1     customers                       zip           0     0.0
2     customers                      city           0     0.0
3     customers               signup_date           0     0.0
4     customers                    gender           0     0.0
..          ...                       ...         ...     ...     ...
91  web_traffic           unique_visitors           0     0.0
92  web_traffic                page_views           0     0.0
93  web_traffic               bounce_rate           0     0.0
94  web_traffic  avg_session_duration_sec           0     0.0
95  web_traffic            traffic_source           0     0.0

[96 rows x 5 columns]

# 3. Cardinality

In [6]:
card_records = []

for table, df in dfs.items():
    n = len(df)
    for col in df.columns:
        n_unique = df[col].nunique(dropna=True)
        ratio    = n_unique / n if n > 0 else 0
        
        if ratio > HIGH_CARD_THRESHOLD:
            card_type = '🔑 high (PK/FK candidate)'
        elif ratio < LOW_CARD_THRESHOLD:
            card_type = '🏷️  low (category/enum)'
        else:
            card_type = '📊 medium'
        
        # Sample top values for low-cardinality cols
        if ratio < LOW_CARD_THRESHOLD and n_unique <= 20:
            top_vals = df[col].value_counts().head(5)
            sample = ', '.join([f"{v}({c})" for v,c in top_vals.items()])
        else:
            sample = '—'
        
        card_records.append({
            'table':       table,
            'column':      col,
            'n_unique':    n_unique,
            'unique_ratio': round(ratio, 4),
            'cardinality': card_type,
            'top_values':  sample,
        })

card_df = pd.DataFrame(card_records)

print("Cardinality Summary\n")

for table, grp in card_df.groupby('table'):
    print(f"\n── {table} ({dfs[table].shape[0]:,} rows) ──")
    display(grp[['column','n_unique','unique_ratio','cardinality','top_values']]
            .reset_index(drop=True))

Cardinality Summary


── customers (121,930 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,customer_id,121930,1.0000,🔑 high (PK/FK candidate),—
1,zip,31491,0.2583,📊 medium,—
2,city,42,0.0003,🏷️ low (category/enum),—
3,signup_date,3941,0.0323,🏷️ low (category/enum),—
4,gender,3,0.0000,🏷️ low (category/enum),"Female(59640), Male(57457), Non-binary(4833)"
5,age_group,5,0.0000,🏷️ low (category/enum),"25-34(36342), 35-44(31920), 45-54(23172), 18-2..."
6,acquisition_channel,6,0.0000,🏷️ low (category/enum),"organic_search(36450), social_media(24448), pa..."

── geography (39,948 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,zip,39948,1.0000,🔑 high (PK/FK candidate),—
1,city,42,0.0011,🏷️ low (category/enum),—
2,region,3,0.0001,🏷️ low (category/enum),"East(18929), Central(14512), West(6507)"
3,district,39,0.0010,🏷️ low (category/enum),—

── inventory (60,247 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,snapshot_date,126,0.0021,🏷️ low (category/enum),—
1,product_id,1624,0.0270,🏷️ low (category/enum),—
2,stock_on_hand,1895,0.0315,🏷️ low (category/enum),—
3,units_received,360,0.0060,🏷️ low (category/enum),—
4,units_sold,303,0.0050,🏷️ low (category/enum),—
5,stockout_days,29,0.0005,🏷️ low (category/enum),—
6,days_of_supply,9289,0.1542,📊 medium,—
7,fill_rate,29,0.0005,🏷️ low (category/enum),—
8,stockout_flag,2,0.0000,🏷️ low (category/enum),"1(40571), 0(19676)"
9,overstock_flag,2,0.0000,🏷️ low (category/enum),"1(45942), 0(14305)"
10,reorder_flag,1,0.0000,🏷️ low (category/enum),0(60247)
11,sell_through_rate,4017,0.0667,📊 medium,—
12,product_name,1465,0.0243,🏷️ low (category/enum),—
13,category,4,0.0001,🏷️ low (category/enum),"Streetwear(31020), Outdoor(21050), GenZ(4674),..."
14,segment,8,0.0001,🏷️ low (category/enum),"Activewear(18290), Everyday(13598), Performanc..."
15,year,11,0.0002,🏷️ low (category/enum),"2018(6106), 2017(6084), 2016(5927), 2015(5872)..."
16,month,12,0.0002,🏷️ low (category/enum),"8(5541), 7(5238), 9(5201), 4(5181), 12(5146)"

── order_items (714,669 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,order_id,646945,0.9052,📊 medium,—
1,product_id,1598,0.0022,🏷️ low (category/enum),—
2,quantity,8,0.0000,🏷️ low (category/enum),"1(89623), 5(89608), 6(89500), 2(89394), 7(89348)"
3,unit_price,501330,0.7015,📊 medium,—
4,discount_amount,204449,0.2861,📊 medium,—
5,promo_id,50,0.0001,🏷️ low (category/enum),—
6,promo_id_2,2,0.0000,🏷️ low (category/enum),"PROMO-0015(132), PROMO-0025(74)"

── orders (646,945 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,order_id,646945,1.0000,🔑 high (PK/FK candidate),—
1,order_date,3833,0.0059,🏷️ low (category/enum),—
2,customer_id,90246,0.1395,📊 medium,—
3,zip,29932,0.0463,🏷️ low (category/enum),—
4,order_status,6,0.0000,🏷️ low (category/enum),"delivered(516716), cancelled(59462), returned(..."
5,payment_method,5,0.0000,🏷️ low (category/enum),"credit_card(356352), paypal(97018), cod(96681)..."
6,device_type,3,0.0000,🏷️ low (category/enum),"mobile(291482), desktop(258855), tablet(96608)"
7,order_source,6,0.0000,🏷️ low (category/enum),"organic_search(181495), paid_search(141652), s..."

── payments (646,945 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,order_id,646945,1.0000,🔑 high (PK/FK candidate),—
1,payment_method,5,0.0000,🏷️ low (category/enum),"credit_card(356352), paypal(97018), cod(96681)..."
2,payment_value,595420,0.9204,📊 medium,—
3,installments,5,0.0000,🏷️ low (category/enum),"1(262866), 3(218949), 6(109910), 12(54126), 2(..."

── products (2,412 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,product_id,2412,1.0000,🔑 high (PK/FK candidate),—
1,product_name,2172,0.9005,📊 medium,—
2,category,4,0.0017,🏷️ low (category/enum),"Streetwear(1320), Outdoor(743), Casual(201), G..."
3,segment,8,0.0033,🏷️ low (category/enum),"Activewear(598), Everyday(405), Performance(34..."
4,size,4,0.0017,🏷️ low (category/enum),"S(603), M(603), L(603), XL(603)"
5,color,10,0.0041,🏷️ low (category/enum),"orange(242), black(242), silver(241), green(24..."
6,price,1990,0.8250,📊 medium,—
7,cogs,2381,0.9871,🔑 high (PK/FK candidate),—

── promotions (50 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,promo_id,50,1.00,🔑 high (PK/FK candidate),—
1,promo_name,50,1.00,🔑 high (PK/FK candidate),—
2,promo_type,2,0.04,🏷️ low (category/enum),"percentage(45), fixed(5)"
3,discount_value,6,0.12,📊 medium,—
4,start_date,50,1.00,🔑 high (PK/FK candidate),—
5,end_date,50,1.00,🔑 high (PK/FK candidate),—
6,applicable_category,2,0.04,🏷️ low (category/enum),"Streetwear(5), Outdoor(5)"
7,promo_channel,5,0.10,📊 medium,—
8,stackable_flag,2,0.04,🏷️ low (category/enum),"0(38), 1(12)"
9,min_order_value,5,0.10,📊 medium,—

── returns (39,939 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,return_id,39939,1.0000,🔑 high (PK/FK candidate),—
1,order_id,36062,0.9029,📊 medium,—
2,product_id,1286,0.0322,🏷️ low (category/enum),—
3,return_date,3806,0.0953,📊 medium,—
4,return_reason,5,0.0001,🏷️ low (category/enum),"wrong_size(13967), defective(8020), not_as_des..."
5,return_quantity,8,0.0002,🏷️ low (category/enum),"1(13581), 2(8633), 3(6050), 4(4464), 5(3127)"
6,refund_amount,39560,0.9905,🔑 high (PK/FK candidate),—

── reviews (113,551 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,review_id,113551,1.0000,🔑 high (PK/FK candidate),—
1,order_id,111369,0.9808,🔑 high (PK/FK candidate),—
2,product_id,1412,0.0124,🏷️ low (category/enum),—
3,customer_id,48676,0.4287,📊 medium,—
4,review_date,3825,0.0337,🏷️ low (category/enum),—
5,rating,5,0.0000,🏷️ low (category/enum),"5(45256), 4(36412), 3(17016), 2(9095), 1(5772)"
6,review_title,18,0.0002,🏷️ low (category/enum),"Very satisfied(11450), Highly recommend(11407)..."

── sales (3,833 rows) ──

    column  n_unique  unique_ratio               cardinality top_values
0     Date      3833           1.0  🔑 high (PK/FK candidate)          —
1  Revenue      3833           1.0  🔑 high (PK/FK candidate)          —
2     COGS      3833           1.0  🔑 high (PK/FK candidate)          —

── sample_submission (548 rows) ──

    column  n_unique  unique_ratio               cardinality top_values
0     Date       548           1.0  🔑 high (PK/FK candidate)          —
1  Revenue       548           1.0  🔑 high (PK/FK candidate)          —
2     COGS       548           1.0  🔑 high (PK/FK candidate)          —

── shipments (566,067 rows) ──

          column  n_unique  unique_ratio               cardinality top_values
0       order_id    566067        1.0000  🔑 high (PK/FK candidate)          —
1      ship_date      3831        0.0068   🏷️  low (category/enum)          —
2  delivery_date      3831        0.0068   🏷️  low (category/enum)          —
3   shipping_fee      1856        0.0033   🏷️  low (category/enum)          —

── web_traffic (3,652 rows) ──

,column,n_unique,unique_ratio,cardinality,top_values
0,date,3652,1.0000,🔑 high (PK/FK candidate),—
1,sessions,3447,0.9439,📊 medium,—
2,unique_visitors,3382,0.9261,📊 medium,—
3,page_views,3620,0.9912,🔑 high (PK/FK candidate),—
4,bounce_rate,261,0.0715,📊 medium,—
5,avg_session_duration_sec,1771,0.4849,📊 medium,—
6,traffic_source,6,0.0016,🏷️ low (category/enum),"organic_search(1090), paid_search(784), social..."

# 4. Foreign Key Detection

In [7]:
# ── STEP 4a: Detect Primary Key candidates ───────────────────────────────
pk_candidates = {}   # table → [col, ...]

for table, df in dfs.items():
    pks = []
    for col in df.columns:
        n_unique = df[col].nunique(dropna=True)
        n_null   = df[col].isnull().sum()
        ratio    = n_unique / len(df) if len(df) > 0 else 0
        # PK: fully unique, no nulls
        if n_unique == len(df) and n_null == 0:
            pks.append(col)
    pk_candidates[table] = pks

print("🔑 Primary Key Candidates:")
for table, pks in pk_candidates.items():
    pk_str = ', '.join(pks) if pks else '(none found)'
    print(f"   {table:30s} → {pk_str}")

# ── STEP 4b: Detect FK candidates ───────────────────────────────────────
print("\n" + "─"*60)
print("🔗 Foreign Key Candidates (col values ⊆ PK values in another table):")
print("─"*60)

fk_links = []

for src_table, src_df in dfs.items():
    for src_col in src_df.columns:
        src_vals = set(src_df[src_col].dropna().unique())
        if len(src_vals) == 0:
            continue
        
        for ref_table, ref_pks in pk_candidates.items():
            if ref_table == src_table:
                continue
            for ref_pk in ref_pks:
                ref_vals = set(dfs[ref_table][ref_pk].dropna().unique())
                if len(ref_vals) == 0:
                    continue
                
                # Check: src values are subset of ref PK values
                coverage = len(src_vals & ref_vals) / len(src_vals)
                
                if coverage >= 0.80:  # 80%+ match → likely FK
                    fk_links.append({
                        'from_table':  src_table,
                        'from_col':    src_col,
                        'to_table':    ref_table,
                        'to_col':      ref_pk,
                        'coverage_%':  round(coverage * 100, 1),
                        'src_unique':  len(src_vals),
                        'ref_unique':  len(ref_vals),
                    })

if fk_links:
    fk_df = pd.DataFrame(fk_links).sort_values('coverage_%', ascending=False)
    
    for _, row in fk_df.iterrows():
        bar_len = int(row['coverage_%'] / 5)
        bar = '█' * bar_len + '░' * (20 - bar_len)
        print(f"  {row['from_table']}.{row['from_col']:20s}  →  "
              f"{row['to_table']}.{row['to_col']:15s}  "
              f"{bar} {row['coverage_%']}%")
    
    print("\nFull FK table:")
    display(fk_df.reset_index(drop=True))
else:
    print("  No FK candidates found (try lowering the coverage threshold).")

🔑 Primary Key Candidates:
   customers                      → customer_id
   geography                      → zip
   inventory                      → (none found)
   order_items                    → (none found)
   orders                         → order_id
   payments                       → order_id
   products                       → product_id
   promotions                     → promo_id, promo_name, start_date, end_date
   returns                        → return_id
   reviews                        → review_id
   sales                          → Date, Revenue, COGS
   sample_submission              → Date, Revenue, COGS
   shipments                      → order_id
   web_traffic                    → date

────────────────────────────────────────────────────────────
🔗 Foreign Key Candidates (col values ⊆ PK values in another table):
────────────────────────────────────────────────────────────
  customers.zip                   →  geography.zip              ████████████████████ 100.0%
  inventory.snapshot_date         →  sales.Date             ████████████████████ 100.0%
  inventory.units_sold            →  products.product_id       ████████████████████ 100.0%
  inventory.units_received        →  products.product_id       ████████████████████ 100.0%
  inventory.product_id            →  products.product_id       ████████████████████ 100.0%
  order_items.order_id              →  orders.order_id         ████████████████████ 100.0%
  order_items.order_id              →  payments.order_id         ████████████████████ 100.0%
  inventory.month                 →  products.product_id       ████████████████████ 100.0%
  order_items.product_id            →  products.product_id       ████████████████████ 100.0%
  inventory.year                  →  products.product_id       ████████████████████ 100.0%
  promotions.end_date              →  sales.Date             ████████████████████ 100.0%
  promotions.start_date            →  sales.Date             ████████████████████ 100.0%
  promotions.discount_value        →  products.product_id       ████████████████████ 100.0%
  orders.order_id              →  payments.order_id         ████████████████████ 100.0%
  orders.order_date            →  sales.Date             ████████████████████ 100.0%
  orders.zip                   →  geography.zip              ████████████████████ 100.0%
  orders.customer_id           →  customers.customer_id      ████████████████████ 100.0%
  payments.order_id              →  orders.order_id         ████████████████████ 100.0%
  order_items.quantity              →  products.product_id       ████████████████████ 100.0%
  order_items.promo_id_2            →  promotions.promo_id         ████████████████████ 100.0%
  order_items.promo_id              →  promotions.promo_id         ████████████████████ 100.0%
  web_traffic.date                  →  sales.Date             ████████████████████ 100.0%
  shipments.order_id              →  orders.order_id         ████████████████████ 100.0%
  shipments.order_id              →  payments.order_id         ████████████████████ 100.0%
  reviews.review_date           →  sales.Date             ████████████████████ 100.0%
  reviews.rating                →  customers.customer_id      ████████████████████ 100.0%
  reviews.rating                →  geography.zip              ████████████████████ 100.0%
  reviews.customer_id           →  customers.customer_id      ████████████████████ 100.0%
  reviews.product_id            →  products.product_id       ████████████████████ 100.0%
  returns.return_quantity       →  products.product_id       ████████████████████ 100.0%
  reviews.order_id              →  orders.order_id         ████████████████████ 100.0%
  reviews.order_id              →  shipments.order_id         ████████████████████ 100.0%
  promotions.discount_value        →  geography.zip              ████████████████████ 100.0%
  promotions.discount_value        →  customers.customer_id      ████████████████████ 100.0%
  payments.installments          →  products.product_id       ████████████████████ 100.0%
  payments.installments          →  geography.zip              ████████████████████ 100.0%
  payments.installments          →  customers.customer_id      ████████████████████ 100.0%
  promotions.end_date              →  web_traffic.date             ████████████████████ 100.0%
  returns.order_id              →  orders.order_id         ████████████████████ 100.0%
  promotions.start_date            →  web_traffic.date             ████████████████████ 100.0%
  reviews.rating                →  products.product_id       ████████████████████ 100.0%
  shipments.delivery_date         →  sales.Date             ████████████████████ 100.0%
  shipments.ship_date             →  sales.Date             ████████████████████ 100.0%
  returns.order_id              →  shipments.order_id         ████████████████████ 100.0%
  returns.order_id              →  payments.order_id         ████████████████████ 100.0%
  returns.return_date           →  sales.Date             ████████████████████ 100.0%
  returns.product_id            →  products.product_id       ████████████████████ 100.0%
  reviews.order_id              →  payments.order_id         ████████████████████ 100.0%
  customers.signup_date           →  sales.Date             ███████████████████░ 97.1%
  inventory.stockout_days         →  products.product_id       ███████████████████░ 96.6%
  inventory.stock_on_hand         →  products.product_id       ███████████████████░ 96.3%
  returns.return_date           →  web_traffic.date             ███████████████████░ 95.5%
  reviews.review_date           →  web_traffic.date             ███████████████████░ 95.5%
  orders.order_date            →  web_traffic.date             ███████████████████░ 95.3%
  shipments.delivery_date         →  web_traffic.date             ███████████████████░ 95.3%
  shipments.ship_date             →  web_traffic.date             ███████████████████░ 95.3%
  sales.Date                  →  web_traffic.date             ███████████████████░ 95.3%
  inventory.snapshot_date         →  web_traffic.date             ███████████████████░ 95.2%
  customers.signup_date           →  web_traffic.date             ██████████████████░░ 92.7%
  inventory.month                 →  customers.customer_id      ██████████████████░░ 91.7%
  inventory.month                 →  geography.zip              ██████████████████░░ 91.7%
  returns.return_quantity       →  payments.order_id         █████████████████░░░ 87.5%
  returns.return_quantity       →  shipments.order_id         █████████████████░░░ 87.5%
  returns.return_quantity       →  geography.zip              █████████████████░░░ 87.5%
  order_items.order_id              →  shipments.order_id         █████████████████░░░ 87.5%
  order_items.quantity              →  customers.customer_id      █████████████████░░░ 87.5%
  order_items.quantity              →  shipments.order_id         █████████████████░░░ 87.5%
  order_items.quantity              →  orders.order_id         █████████████████░░░ 87.5%
  order_items.quantity              →  payments.order_id         █████████████████░░░ 87.5%
  returns.return_quantity       →  customers.customer_id      █████████████████░░░ 87.5%
  order_items.quantity              →  geography.zip              █████████████████░░░ 87.5%
  orders.order_id              →  shipments.order_id         █████████████████░░░ 87.5%
  returns.return_quantity       →  orders.order_id         █████████████████░░░ 87.5%
  payments.order_id              →  shipments.order_id         █████████████████░░░ 87.5%
  promotions.discount_value        →  orders.order_id         ████████████████░░░░ 83.3%
  promotions.discount_value        →  payments.order_id         ████████████████░░░░ 83.3%
  promotions.discount_value        →  shipments.order_id         ████████████████░░░░ 83.3%
  inventory.stockout_days         →  customers.customer_id      ████████████████░░░░ 82.8%
  inventory.year                  →  payments.order_id         ████████████████░░░░ 81.8%
  inventory.year                  →  orders.order_id         ████████████████░░░░ 81.8%
  payments.installments          →  shipments.order_id         ████████████████░░░░ 80.0%
  payments.installments          →  orders.order_id         ████████████████░░░░ 80.0%
  reviews.rating                →  shipments.order_id         ████████████████░░░░ 80.0%
  reviews.rating                →  orders.order_id         ████████████████░░░░ 80.0%
  reviews.rating                →  payments.order_id         ████████████████░░░░ 80.0%

Full FK table:

,from_table,from_col,to_table,to_col,coverage_%,src_unique,ref_unique
0,customers,zip,geography,zip,100.0,31491,39948
1,inventory,snapshot_date,sales,Date,100.0,126,3833
2,inventory,units_sold,products,product_id,100.0,303,2412
3,inventory,units_received,products,product_id,100.0,360,2412
4,inventory,product_id,products,product_id,100.0,1624,2412
...,...,...,...,...,...,...,...
80,payments,installments,shipments,order_id,80.0,5,566067
81,payments,installments,orders,order_id,80.0,5,646945
82,reviews,rating,shipments,order_id,80.0,5,566067
83,reviews,rating,orders,order_id,80.0,5,646945
84,reviews,rating,payments,order_id,80.0,5,646945

# 5. Entity Relationship Diagram

In [8]:
# Print Mermaid ERD bạn có thể paste vào https://mermaid.live
lines = ["```mermaid", "erDiagram"]

# Tables with columns
for table, df in dfs.items():
    lines.append(f"  {table.upper()} {{")
    for col in df.columns:
        dtype = dtype_category(str(df[col].dtype))
        # Mark PKs
        pk_mark = " PK" if col in pk_candidates.get(table, []) else ""
        lines.append(f"    {dtype} {col}{pk_mark}")
    lines.append("  }")

# Relationships from FK detection
if fk_links:
    added = set()
    for link in fk_links:
        key = (link['from_table'], link['to_table'])
        if key not in added:
            lines.append(f"  {link['to_table'].upper()} ||--o{{ {link['from_table'].upper()} : \"{link['to_col']} → {link['from_col']}\"")
            added.add(key)

lines.append("```")
mermaid_src = "\n".join(lines)

print("Paste vào https://mermaid.live để xem ERD diagram:\n")
print(mermaid_src)

Paste vào https://mermaid.live để xem ERD diagram:

```mermaid
erDiagram
  CUSTOMERS {
    integer customer_id PK
    integer zip
    string/object city
    string/object signup_date
    string/object gender
    string/object age_group
    string/object acquisition_channel
  }
  GEOGRAPHY {
    integer zip PK
    string/object city
    string/object region
    string/object district
  }
  INVENTORY {
    string/object snapshot_date
    integer product_id
    integer stock_on_hand
    integer units_received
    integer units_sold
    integer stockout_days
    float days_of_supply
    float fill_rate
    integer stockout_flag
    integer overstock_flag
    integer reorder_flag
    float sell_through_rate
    string/object product_name
    string/object category
    string/object segment
    integer year
    integer month
  }
  ORDER_ITEMS {
    integer order_id
    integer product_id
    integer quantity
    float unit_price
    float discount_amount
    string/object promo_id
    string/object promo_id_2
  }
  ORDERS {
    integer order_id PK
    string/object order_date
    integer customer_id
    integer zip
    string/object order_status
    string/object payment_method
    string/object device_type
    string/object order_source
  }
  PAYMENTS {
    integer order_id PK
    string/object payment_method
    float payment_value
    integer installments
  }
  PRODUCTS {
    integer product_id PK
    string/object product_name
    string/object category
    string/object segment
    string/object size
    string/object color
    float price
    float cogs
  }
  PROMOTIONS {
    string/object promo_id PK
    string/object promo_name PK
    string/object promo_type
    float discount_value
    string/object start_date PK
    string/object end_date PK
    string/object applicable_category
    string/object promo_channel
    integer stackable_flag
    integer min_order_value
  }
  RETURNS {
    string/object return_id PK
    integer order_id
    integer product_id
    string/object return_date
    string/object return_reason
    integer return_quantity
    float refund_amount
  }
  REVIEWS {
    string/object review_id PK
    integer order_id
    integer product_id
    integer customer_id
    string/object review_date
    integer rating
    string/object review_title
  }
  SALES {
    string/object Date PK
    float Revenue PK
    float COGS PK
  }
  SAMPLE_SUBMISSION {
    string/object Date PK
    float Revenue PK
    float COGS PK
  }
  SHIPMENTS {
    integer order_id PK
    string/object ship_date
    string/object delivery_date
    float shipping_fee
  }
  WEB_TRAFFIC {
    string/object date PK
    integer sessions
    integer unique_visitors
    integer page_views
    float bounce_rate
    float avg_session_duration_sec
    string/object traffic_source
  }
  GEOGRAPHY ||--o{ CUSTOMERS : "zip → zip"
  SALES ||--o{ CUSTOMERS : "Date → signup_date"
  WEB_TRAFFIC ||--o{ CUSTOMERS : "date → signup_date"
  SALES ||--o{ INVENTORY : "Date → snapshot_date"
  WEB_TRAFFIC ||--o{ INVENTORY : "date → snapshot_date"
  PRODUCTS ||--o{ INVENTORY : "product_id → product_id"
  CUSTOMERS ||--o{ INVENTORY : "customer_id → stockout_days"
  ORDERS ||--o{ INVENTORY : "order_id → year"
  PAYMENTS ||--o{ INVENTORY : "order_id → year"
  GEOGRAPHY ||--o{ INVENTORY : "zip → month"
  ORDERS ||--o{ ORDER_ITEMS : "order_id → order_id"
  PAYMENTS ||--o{ ORDER_ITEMS : "order_id → order_id"
  SHIPMENTS ||--o{ ORDER_ITEMS : "order_id → order_id"
  PRODUCTS ||--o{ ORDER_ITEMS : "product_id → product_id"
  CUSTOMERS ||--o{ ORDER_ITEMS : "customer_id → quantity"
  GEOGRAPHY ||--o{ ORDER_ITEMS : "zip → quantity"
  PROMOTIONS ||--o{ ORDER_ITEMS : "promo_id → promo_id"
  PAYMENTS ||--o{ ORDERS : "order_id → order_id"
  SHIPMENTS ||--o{ ORDERS : "order_id → order_id"
  SALES ||--o{ ORDERS : "Date → order_date"
  WEB_TRAFFIC ||--o{ ORDERS : "date → order_date"
  CUSTOMERS ||--o{ ORDERS : "customer_id → customer_id"
  GEOGRAPHY ||--o{ ORDERS : "zip → zip"
  ORDERS ||--o{ PAYMENTS : "order_id → order_id"
  SHIPMENTS ||--o{ PAYMENTS : "order_id → order_id"
  CUSTOMERS ||--o{ PAYMENTS : "customer_id → installments"
  GEOGRAPHY ||--o{ PAYMENTS : "zip → installments"
  PRODUCTS ||--o{ PAYMENTS : "product_id → installments"
  CUSTOMERS ||--o{ PROMOTIONS : "customer_id → discount_value"
  GEOGRAPHY ||--o{ PROMOTIONS : "zip → discount_value"
  ORDERS ||--o{ PROMOTIONS : "order_id → discount_value"
  PAYMENTS ||--o{ PROMOTIONS : "order_id → discount_value"
  PRODUCTS ||--o{ PROMOTIONS : "product_id → discount_value"
  SHIPMENTS ||--o{ PROMOTIONS : "order_id → discount_value"
  SALES ||--o{ PROMOTIONS : "Date → start_date"
  WEB_TRAFFIC ||--o{ PROMOTIONS : "date → start_date"
  ORDERS ||--o{ RETURNS : "order_id → order_id"
  PAYMENTS ||--o{ RETURNS : "order_id → order_id"
  SHIPMENTS ||--o{ RETURNS : "order_id → order_id"
  PRODUCTS ||--o{ RETURNS : "product_id → product_id"
  SALES ||--o{ RETURNS : "Date → return_date"
  WEB_TRAFFIC ||--o{ RETURNS : "date → return_date"
  CUSTOMERS ||--o{ RETURNS : "customer_id → return_quantity"
  GEOGRAPHY ||--o{ RETURNS : "zip → return_quantity"
  ORDERS ||--o{ REVIEWS : "order_id → order_id"
  PAYMENTS ||--o{ REVIEWS : "order_id → order_id"
  SHIPMENTS ||--o{ REVIEWS : "order_id → order_id"
  PRODUCTS ||--o{ REVIEWS : "product_id → product_id"
  CUSTOMERS ||--o{ REVIEWS : "customer_id → customer_id"
  SALES ||--o{ REVIEWS : "Date → review_date"
  WEB_TRAFFIC ||--o{ REVIEWS : "date → review_date"
  GEOGRAPHY ||--o{ REVIEWS : "zip → rating"
  WEB_TRAFFIC ||--o{ SALES : "date → Date"
  ORDERS ||--o{ SHIPMENTS : "order_id → order_id"
  PAYMENTS ||--o{ SHIPMENTS : "order_id → order_id"
  SALES ||--o{ SHIPMENTS : "Date → ship_date"
  WEB_TRAFFIC ||--o{ SHIPMENTS : "date → ship_date"
  SALES ||--o{ WEB_TRAFFIC : "Date → date"
```

# 6. Master Summary

In [9]:
summary_rows = []

for table, df in dfs.items():
    total_nulls = df.isnull().sum().sum()
    total_cells = df.shape[0] * df.shape[1]
    null_pct_overall = total_nulls / total_cells * 100
    
    dtype_counts = pd.Series([dtype_category(str(df[c].dtype)) for c in df.columns]).value_counts().to_dict()
    
    pk_cols = pk_candidates.get(table, [])
    fk_cols = [l['from_col'] for l in fk_links if l['from_table'] == table]
    
    summary_rows.append({
        'table':         table,
        'rows':          f"{len(df):,}",
        'cols':          len(df.columns),
        'null_%':        f"{null_pct_overall:.1f}%",
        'pk_cols':       ', '.join(pk_cols) or '—',
        'fk_cols':       ', '.join(set(fk_cols)) or '—',
        'dtypes':        ' | '.join([f"{k}×{v}" for k,v in dtype_counts.items()]),
    })

summary = pd.DataFrame(summary_rows)

print("="*80)
print("MASTER SCHEMA SUMMARY")
print("="*80)
display(summary.style
        .set_table_styles([{
            'selector': 'th',
            'props': [('background-color','#1a1a2e'),('color','white'),('padding','8px 14px'),('font-size','13px')]
        },{
            'selector': 'td',
            'props': [('padding','6px 12px'),('font-size','13px')]
        }])
        .set_caption("Auto-generated by 00_schema_overview.ipynb")
)

================================================================================
MASTER SCHEMA SUMMARY
================================================================================